eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
openapi:
    service:
        title: mail-service doc
        url: http://localhost:8080
        version: 1.0.0
server:
    port: 0
service: ''
spring:
    application:
        name: mail-service
    data:
        mongodb:
            authentication-database: admin
            database: my-assistance-db
            host: localhost
            password: 22558800
            port: 27017
            username: oguzmuay
springdoc:
    api-docs:
        path: /mail-service/v3/api-docs
swagger-ui:
    path: /mail-service/swagger-ui.html
